export const getYears=()=>{
  return ["112-2","112-1","111-1"];
}
export const getSchool=()=>{
  return ["三民國小","三民國中","xxx國中"];
}
export const getData=()=>{
  return [{
    time:"111-1",
    name:"啊一",
    account:"1@gmail.com",
    phone:"0911111111",
    team:"三民國小",
    schoolRole:"校長",
    lecture:"",
    associationRole:"",
    identity:"PRI",
  },{
    time:"111-1",
    name:"啊二",
    account:"2@gmail.com",
    phone:"0922222222",
    team:"三民國小",
    schoolRole:"教務主任",
    lecture:"",
    associationRole:"",
    identity:"DIR-2",
  },{
    time:"111-1",
    name:"啊三",
    account:"3@gmail.com",
    phone:"0933333333",
    team:"三民國小",
    schoolRole:"六年級導師",
    lecture:"社會",
    associationRole:"國小社會領召",
    identity:"TEA",
  },{
    time:"111-1",
    name:"啊四",
    account:"4@gmail.com",
    phone:"0944444444",
    team:"三民國小",
    schoolRole:"科任老師、coach",
    lecture:"自然",
    associationRole:"",
    identity:"TEA",
  },{
    time:"111-1",
    name:"啊五",
    account:"5@gmail.com",
    phone:"0955555555",
    team:"三民國中",
    schoolRole:"校長",
    lecture:"",
    associationRole:"",
    identity:"PRI",
  },{
    time:"111-1",
    name:"啊六",
    account:"6@gmail.com",
    phone:"0966666666",
    team:"三民國中",
    schoolRole:"行政主任",
    lecture:"",
    associationRole:"",
    identity:"DIR-1",
  },{
    time:"111-1",
    name:"啊七",
    account:"7@gmail.com",
    phone:"0977777777",
    team:"三民國中",
    schoolRole:"三年級導師、Mentor",
    lecture:"數學、國語",
    associationRole:"",
    identity:"TEA",
  }];
}