export let data1 = [
    [
        {
            "id": "c0ba9b9d-f825-4c9b-8120-144ee471b04d",
            "type": "段落標題",
            "bold": true,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 18,
            "content": "【第一部分】教學力自評",
            "rowSpan": "1",
            "colSpan": "full",
            "simplifiedVersion": false
        },
        {
            "id": "5bb80f4e-7a1d-4eb8-885f-6a160247be42",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "47df77dd-9164-4ce8-a362-20dc918b899a",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "23588af2-1883-4ca4-a9cf-d488cd57af57",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "269ae544-cdc8-4434-ba73-f7a9c5f03e7a",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "填寫說明：以下是教學力現況自評，請自我檢視已達成的程度，選取符合描述的選項，以利後續建立自我專業發展的依據。",
            "rowSpan": "1",
            "colSpan": "4",
            "simplifiedVersion": false
        },
        {
            "id": "4fa59595-3b6f-42b9-ac91-6aeb66cedf5f",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "f6dbb316-6fb6-4b49-959c-843c573f966a",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "7a35fc86-bb5d-4499-b1c8-9113a8d743db",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "701bb900-941a-4545-9ed4-5e87065764ac",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "發展項目一",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "ecd7a33e-0880-4898-8bc7-55547bd02207",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "發展項目二 ",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "aba19bc5-8a1a-4890-bf08-95bc132b39f1",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "質性",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "50402098-8257-4f0e-a36b-ade259a5c08c",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "量化",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "7383d897-3e6b-4b35-82a4-17c2f98cbcd7",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "1. 班級經營與文化",
            "rowSpan": "2",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "ef6aea47-4057-42df-972c-b4d853f02aa2",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "1.1 給所有人機會和期待",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "b5d24ca9-7283-4df5-a78e-448cb4d62973",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "a6973b41-fe78-4a10-8136-97e9ae316873",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "b384c8a8-b835-437e-95d7-766d13aac417",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "ad7ef77c-ad8d-4953-a7ae-adfa81e722f2",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "94e67575-8104-4c46-8156-3d7e59d68275",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "fd158678-b6f0-4da2-b58a-021c8cfe0eae",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "b156c1b0-21cb-41ac-bac3-7b88e8c69141",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "b379805d-cb68-4a74-9194-c370da99f6ca",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "7387b137-fae6-43c5-8850-882ff3549e79",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "2f27e303-6361-4765-af1c-fc9033019db8",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ]
];