export let data1 = [
    [
        {
            "id": "c0ba9b9d-f825-4c9b-8120-144ee471b04d",
            "type": "段落標題",
            "bold": true,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 18,
            "content": "【第一部分】教學力自評",
            "rowSpan": "1",
            "colSpan": "full",
            "simplifiedVersion": false
        },
        {
            "id": "5bb80f4e-7a1d-4eb8-885f-6a160247be42",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "47df77dd-9164-4ce8-a362-20dc918b899a",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "23588af2-1883-4ca4-a9cf-d488cd57af57",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "269ae544-cdc8-4434-ba73-f7a9c5f03e7a",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "填寫說明：以下是教學力現況自評，請自我檢視已達成的程度，選取符合描述的選項，以利後續建立自我專業發展的依據。",
            "rowSpan": "1",
            "colSpan": "4",
            "simplifiedVersion": false
        },
        {
            "id": "4fa59595-3b6f-42b9-ac91-6aeb66cedf5f",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "f6dbb316-6fb6-4b49-959c-843c573f966a",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "7a35fc86-bb5d-4499-b1c8-9113a8d743db",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "701bb900-941a-4545-9ed4-5e87065764ac",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "發展項目一",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "ecd7a33e-0880-4898-8bc7-55547bd02207",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "發展項目二 ",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "aba19bc5-8a1a-4890-bf08-95bc132b39f1",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "質性",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "50402098-8257-4f0e-a36b-ade259a5c08c",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "量化",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "7383d897-3e6b-4b35-82a4-17c2f98cbcd7",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "當期待很高並且所有學生都被支持和鼓勵時，學生可以學得最好。",
            "size": 15,
            "content": "1. 班級經營與文化",
            "rowSpan": "2",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "ef6aea47-4057-42df-972c-b4d853f02aa2",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "顯示更多",
            "size": 15,
            "content": "1.1 給所有人機會和期待",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "b5d24ca9-7283-4df5-a78e-448cb4d62973",
            "type": "單選題",
            "bold": false,
            "color": "light",
            "history": "歷史",
            "more": "",
            "size": 15,
            "content": "[\"教師很少展現對所有學習者有高期待的學習成就。\",\"老師有時會展示出對所有學生學習和成就的高期待，但沒有提供支援或支援不符合學生的需求，以幫助達成這些期待。\",\"老師始終或幾乎始終展現/示範對所有學習者在學習和成就上的高期待，並提供與學習者需求相匹配的支持以幫助實現這些期待。\",\"老師傳達的課堂常規，流程和期望有一定的清晰度，符合學生的需求並支持我們的共同目標：學習。\"]",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "a6973b41-fe78-4a10-8136-97e9ae316873",
            "type": "單選題",
            "bold": false,
            "color": "light",
            "history": "歷史",
            "more": "",
            "size": 15,
            "content": "[\"少於60%的學習者參與學習，且教師鮮少鼓勵他們參與。\",\"60-84％的學生參與並受到老師的鼓勵，以及60-84％的傑出學生參與並受到老師的鼓勵。\",\"85-100％的學習者參與並受到老師的鼓勵去參與，以及85-100％的特殊學習者參與並受到老師的鼓勵去參與。\"]",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "b384c8a8-b835-437e-95d7-766d13aac417",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "ad7ef77c-ad8d-4953-a7ae-adfa81e722f2",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "顯示更多",
            "size": 15,
            "content": "1.2 公平的學習條件",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "94e67575-8104-4c46-8156-3d7e59d68275",
            "type": "單選題",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "[\"教師很少展現對所有學習者有高期待的學習成就。\",\"老師有時會展示出對所有學生學習和成就的高期待，但沒有提供支援或支援不符合學生的需求，以幫助達成這些期待。\",\"老師始終或幾乎始終展現/示範對所有學習者在學習和成就上的高期待，並提供與學習者需求相匹配的支持以幫助實現這些期待。\",\"老師傳達的課堂常規，流程和期望有一定的清晰度，符合學生的需求並支持我們的共同目標：學習。\"]",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "fd158678-b6f0-4da2-b58a-021c8cfe0eae",
            "type": "單選題",
            "bold": false,
            "color": "light",
            "history": "110-2：60-84％的學生遵守課堂已經建立的常規和流程…110-1：60-84％的學生遵守課堂已經建立的常規和流程 …",
            "more": "",
            "size": 15,
            "content": "[\"少於60%的學習者參與學習，且教師鮮少鼓勵他們參與。\",\"60-84％的學生參與並受到老師的鼓勵，以及60-84％的傑出學生參與並受到老師的鼓勵。\",\"85-100％的學習者參與並受到老師的鼓勵去參與，以及85-100％的特殊學習者參與並受到老師的鼓勵去參與。\"]",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "b156c1b0-21cb-41ac-bac3-7b88e8c69141",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "2. 學習內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "b379805d-cb68-4a74-9194-c370da99f6ca",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "2.1 課程校準",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "7387b137-fae6-43c5-8850-882ff3549e79",
            "type": "單選題",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "[\"教師很少展現對所有學習者有高期待的學習成就。\",\"老師有時會展示出對所有學生學習和成就的高期待，但沒有提供支援或支援不符合學生的需求，以幫助達成這些期待。\",\"老師始終或幾乎始終展現/示範對所有學習者在學習和成就上的高期待，並提供與學習者需求相匹配的支持以幫助實現這些期待。\",\"老師傳達的課堂常規，流程和期望有一定的清晰度，符合學生的需求並支持我們的共同目標：學習。\"]",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "2f27e303-6361-4765-af1c-fc9033019db8",
            "type": "單選題",
            "bold": false,
            "color": "light",
            "history": "110-2：60-84％的學生遵守課堂已經建立的常規和流程…110-1：60-84％的學生遵守課堂已經建立的常規和流程 …",
            "more": "",
            "size": 15,
            "content": "[\"少於60%的學習者參與學習，且教師鮮少鼓勵他們參與。\",\"60-84％的學生參與並受到老師的鼓勵，以及60-84％的傑出學生參與並受到老師的鼓勵。\",\"85-100％的學習者參與並受到老師的鼓勵去參與，以及85-100％的特殊學習者參與並受到老師的鼓勵去參與。\"]",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "dbd6ac89-42ca-4c97-a510-ef137bdfd748",
            "type": "段落標題",
            "bold": true,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 18,
            "content": "【第二部分】教學力發展計畫",
            "rowSpan": "1",
            "colSpan": "full",
            "simplifiedVersion": false
        },
        {
            "id": "e766cd60-1a6c-4545-a122-18af0d6071fe",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "245391a0-53dd-406f-bd8f-990b2017fd2a",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "cb642b86-be6e-461f-9970-9c8f27264028",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "d7697417-e3c7-4aea-9180-7fc20c89742c",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "填寫說明：以下是教學力現況自評，請自我檢視已達成的程度，選取符合描述的選項，以利後續建立自我專業發展的依據。",
            "rowSpan": "1",
            "colSpan": "4",
            "simplifiedVersion": false
        },
        {
            "id": "41a89850-212b-4e49-b35a-223ea8857dbc",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "06e437e0-54b9-420e-87d0-c2b0bbd80b43",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "4553648f-5d1b-484d-90d0-61c843c9da32",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "07fe53c6-173b-4d64-84f6-472b13d507fa",
            "type": "文字",
            "bold": false,
            "color": "dark",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "4",
            "simplifiedVersion": false
        },
        {
            "id": "416ba75a-58b4-4b34-b006-f690e016262b",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "1a2caea1-2137-4567-ab54-0e82a6a17268",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "1ab419ee-c14d-401e-97fb-c90239cd54ef",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "36537aea-2cc9-48e5-aeee-7ef69b691119",
            "type": "自由填答",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "文字補充說明針對前述擬發展項目，打算透過那些途徑或方法完成？\n請思考多元發展途徑，如\n① 學校 SPTS、校務或專案任務、② 特定主題的學習課程（體系 內或外），或③ 資深同仁或行政主管協助與輔導。\n可同時採取多項發展途徑，每項請具體 說明「人、事、物」的內容",
            "rowSpan": "1",
            "colSpan": "4",
            "simplifiedVersion": false
        },
        {
            "id": "5acbc756-07ef-4bdf-81e2-84f1adebc5b0",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "0adc9ca5-5418-4775-9383-16bcd70febbc",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "08cd8e95-ca5b-43aa-90fd-f2d64742891f",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "add6eaaf-d0ac-484c-b70a-fcac767fd3f0",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "歷史",
            "more": "一些文字巴拉巴拉",
            "size": 15,
            "content": "3-1.設定發展項目",
            "rowSpan": "3",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "df560edf-6b00-45d0-9cd3-13c1398e90f1",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "K3-3-1.",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "1b936842-a5ed-4a29-bacf-e76a439e757a",
            "type": "自由填答",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "請填寫項目說明",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "12ec29b5-1955-4855-8949-2a1598f598d9",
            "type": "自由填答",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "請填寫簡要說明",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "af8e8bf0-60b4-4548-b6eb-cee388e004c8",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "6436df2d-03b2-42cf-8556-e0a1fa07eab3",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "58d7f365-a488-4649-a6fe-e4a6f680d5c7",
            "type": "自由填答",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "請填寫項目說明",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "52fc1c2e-92be-4e67-92a4-e7dd38e17a9b",
            "type": "自由填答",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "請填寫簡要說明",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ],
    [
        {
            "id": "4a60dbcd-a866-4b73-b21b-6ab625ede4fd",
            "type": "null",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "caeb1cba-abcd-4766-ab9b-442589a3a709",
            "type": "文字",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "內容",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "7e97fca8-bd3e-4b83-8c9e-77327311e645",
            "type": "自由填答",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "請填寫項目說明",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        },
        {
            "id": "fd6a2f67-1f80-4571-ad3d-b6ec314e0db3",
            "type": "自由填答",
            "bold": false,
            "color": "light",
            "history": "",
            "more": "",
            "size": 15,
            "content": "請填寫簡要說明",
            "rowSpan": "1",
            "colSpan": "1",
            "simplifiedVersion": false
        }
    ]
];